### ISSUE TITLE
exception in initializing

### ISSUE THREAD

**Issue by pasmophobia** [Propromp/EconomyPro#3]
[09:27:39 INFO]: [EconomyPro] Enabling EconomyPro vrc2
[09:27:39 INFO]: [EconomyPro]  ??????       ???????
[09:27:39 INFO]: [EconomyPro]  ?            ?     ?
[09:27:39 INFO]: [EconomyPro]  ??????       ???????
[09:27:39 INFO]: [EconomyPro]  ?            ?
[09:27:39 INFO]: [EconomyPro]  ??????conomy ?      ro
[09:27:39 INFO]: [EconomyPro] Copyright (c) 2021 Propromp
[09:27:39 INFO]: [EconomyPro] This software is released under MIT license.
[09:27:39 INFO]: [EconomyPro] loading economy system...
[09:27:39 INFO]: [EconomyPro] complete.
[09:27:39 INFO]: [EconomyPro] Vault has been detected. hooking vault economy...
[09:27:39 INFO]: [EconomyPro] - Vault economy hooked! Now registered as a provider
[09:27:39 INFO]: [EconomyPro] complete.
[09:27:39 INFO]: [EconomyPro] hooking enterprise API...
[09:27:39 INFO]: [EconomyPro] - Advanced economy hooked! Now registered as a provider
[09:27:39 INFO]: [EconomyPro] complete.
[09:27:39 INFO]: [EconomyPro] loading banks...
[09:27:39 ERROR]: Error occurred while enabling EconomyPro vrc2 (Is it up to date?)
java.lang.NullPointerException: null
        at net.propromp.economypro.api.PlayerBankAccount.<init>(PlayerBankAccount.kt:7) ~[?:?]
        at net.propromp.economypro.BankDataLoader.load(BankDataLoader.kt:49) ~[?:?]
        at net.propromp.economypro.BankDataLoader.loadAll(BankDataLoader.kt:25) ~[?:?]
        at net.propromp.economypro.Main.onEnable(Main.kt:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1047]

**Comment by pasmophobia** [comment]
Fixed in https://github.com/Propromp/EconomyPro/commit/5ecd448207ed7b9b2d8f2791405422d20c3a35a1
